### ISSUE TITLE
bug(exchange): change  "Contre un échange" radio

### ISSUE THREAD

**Issue by douglasduteil** [Serkels/serkels.eu#1708]
- [x] should add a radio for  "Contre un échange"
- [x] show the select when "Contre un échange" is checked

**Comment by douglasduteil** [comment]
- [ ] should hide the return select field by default
- [ ] when you select with return we should see the return select field with the placeholder in it

**Comment by JNSPK** [comment]
"when you select with return we should see the return select field with the placeholder in it"
I juste don't understand why the placeholder won't show is pretty face . I followed every step from placeholder option trick but with setValue it seems to be overwritten. 

I'm almost at the point where I'll put a Label instead of a placholder ..

**Comment by JNSPK** [comment]
Ok I manage to do it !
